# Web Config
server.port=8080

# Database Config (Persistent File H2 Database)
spring.datasource.url=jdbc:h2:file:./data/wafdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate / JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console Settings (for easy debugging and administration)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Custom WAF Properties
waf.python.url=http://localhost:5000/predict
waf.blocking.enabled=true
waf.confidence.threshold=0.70
waf.bypass.paths=/api/waf/**,/h2-console/**,/favicon.ico,/index.html,/assets/**,/*.js,/*.css,/*.png,/*.jpg
